version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: 'logdb'
    ports:
      - 3307:3306
    volumes:
      - ./my-datavolume:/var/lib/mysql
  api:
    container_name: ems_api_container
    restart: always
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 4040:4040
    depends_on:
      - mysql
    # env_file:
    #   - .env
  web:
    container_name: ems_web_container
    restart: always
    image: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mysql
